version: '2'
services:
    wedding-app:
        image: wedding
        external_links:
            - wedding-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/wedding?useUnicode=true&characterEncoding=utf8&useSSL=false
        ports:
            - 8080:8080
    wedding-mysql:
        extends:
            file: mysql.yml
            service: wedding-mysql
